/* eslint-env serviceworker */

// Declare `self` to avoid issues with TypeScript
declare const self: ServiceWorkerGlobalScope &
  typeof globalThis & { skipWaiting: () => void };

import { clientsClaim } from 'workbox-core';
import { cleanupOutdatedCaches, createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';

// Force the service worker to activate as soon as it's finished installing
self.skipWaiting();
clientsClaim();

// Precache the files generated by the Quasar PWA build
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches that are no longer needed
cleanupOutdatedCaches();

// Fallback to `index.html` for any navigation routes (SPA behavior)
registerRoute(
  new NavigationRoute(
    createHandlerBoundToURL('index.html'),
    { denylist: [/sw\.js$/, /workbox-(.)*\.js$/] }
  )
);
